# Generated by Django 4.1 on 2022-09-06 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_alter_store_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='product/%d/%m/%Y')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('store', models.ForeignKey(db_column='store', on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
            ],
        ),
    ]
